sudo: required
language: rust
rust:
  - stable
  - nightly

cache:
  directories:
    - target

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      rust: nightly

script:
  - cargo build
  - cargo test
  - cd cabi && cargo build && cd ..

after_success:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
      cargo tarpaulin --out Xml
      bash <(curl -s https://codecov.io/bash)
    fi
